name: echo_post
description: A social media post scheduler with AI voice commands.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # Environment
  flutter_dotenv: ^5.1.0

  # HTTP & Networking
  http: ^1.1.0
  url_launcher: ^6.2.2

  # Permissions
  permission_handler: ^11.3.0

  # Social Auth / OAuth - Organized by Login Paradigm
  # ================================================

  # 1. EchoPost App Login (Firebase + Google) - OAuth 2.0
  # firebase_auth: ^5.5.4  # Already listed above
  google_sign_in: ^6.1.6

  # 2. Facebook Business Pages - OAuth 2.0 (Facebook Graph API)
  flutter_facebook_auth: 6.0.4

  # 3. Instagram Creator Account - OAuth 2.0 (Instagram via Facebook)
  # flutter_facebook_auth: 6.0.4  # Reuses Facebook auth with different scopes

  # 4. YouTube Channel Uploads - OAuth 2.0 (YouTube Data API)
  # google_sign_in: ^6.1.6  # Reuses Google auth with YouTube scope
  oauth2_client: 4.2.0 # Optional for manual browser flows
  webview_flutter: ^4.4.2 # Optional for manual OAuth

  # 5. Twitter Posting - OAuth 2.0 with PKCE (required for mobile apps)
  flutter_web_auth_2: ^5.0.0-alpha.3 # Used for Twitter and TikTok OAuth flows
  crypto: ^3.0.3 # Used for PKCE code challenge generation

  # 6. TikTok Video Uploads - OAuth 2.0 with PKCE
  tiktok_sdk_v2: ^0.0.2
  # flutter_web_auth: ^0.6.0  # Already listed above
  # crypto: ^3.0.3  # Already listed above

  # Sharing
  share_plus: ^7.2.1

  # JSON Serialization
  json_annotation: ^4.8.1

  # State Management
  provider: ^6.1.1

  # Audio & Whisper
  record: ^6.0.0

  # Video Player
  video_player: ^2.5.0
  video_thumbnail: ^0.5.3

  # Device Media & EXIF
  image_picker: ^1.0.5
  photo_manager: ^3.0.0-dev.5
  exif: ^3.3.0
  geocoding: ^2.1.1

  # Utilities
  shared_preferences: ^2.2.2
  geolocator: ^14.0.1
  uuid: ^4.2.1
  intl: ^0.20.2
  path: ^1.8.3
  path_provider: ^2.1.2
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

# Flutter Launcher Icons Configuration
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  # Android adaptive icon configuration
  adaptive_icon_foreground: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/transparent.png"
  # iOS configuration
  remove_alpha_ios: false

# TODO: Add your custom launcher icons
# 1. Create/download your 1024x1024 icon images
# 2. Save them in assets/icons/ as app_icon.png and app_icon_foreground.png
# 3. Uncomment the flutter_icons section above
# 4. Run: dart run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - .env_local.json
    - assets/images/
    - assets/icons/
