name: echopost
description: Voice-driven social media posting app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^5.7.0

  # Environment
  flutter_dotenv: ^5.1.0

  # HTTP & Networking
  http: ^0.15.0
  url_launcher: ^6.2.5

  # Social Auth
  flutter_facebook_auth: ^5.0.0
  google_sign_in: ^6.0.0
  twitter_login: ^4.0.0
  tiktok_sdk_v2: ^1.0.0
  oauth2_client: ^4.0.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # State Management
  provider: ^6.1.0

  # Audio & Whisper
  record: ^4.4.0

  # Device Media & EXIF
  image_picker: ^0.8.8+3
  photo_manager: ^3.0.0
  exif: ^1.0.0

  # Utilities
  shared_preferences: ^2.2.0
  geolocator: ^11.0.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/