name: echopost
description: Voice-driven social media posting app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Environment
  flutter_dotenv: ^5.1.0

  # HTTP & Networking
  http: ^1.1.2
  url_launcher: ^6.2.2

  # Social Auth
  flutter_facebook_auth: 6.0.4
  google_sign_in: ^6.1.6
  tiktok_sdk_v2: ^0.0.2
  oauth2_client: 4.2.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # State Management
  provider: ^6.1.1

  # Audio & Whisper
  record: ^5.0.4

  # Video Player
  video_player: ^2.5.0

  # Device Media & EXIF
  image_picker: ^1.0.5
  photo_manager: ^3.0.0-dev.5
  exif: ^3.3.0

  # Utilities
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  crypto: ^3.0.3
  uuid: ^4.2.1
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons Configuration
flutter_icons:
  android: true
  ios: false # Set to false since user only wants Android
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

# TODO: Add your custom launcher icons
# 1. Create/download your 1024x1024 icon images
# 2. Save them in assets/icons/ as app_icon.png and app_icon_foreground.png
# 3. Uncomment the flutter_icons section above
# 4. Run: dart run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - .env.local
    - assets/images/
    - assets/icons/
